### PR TITLE
Geod 514 update auth e2e

### PR DESCRIPTION
**Pull request by oehm-smith**
Stacked on top of #530

### CODE REVIEW

**Comment by oehm-smith** [comment]
Whoops, I forgot to make the username / pw set externally.

**Comment by oehm-smith** [comment]
You can review this one.  And I'll create two more after this is done and merged.

**Comment by oehm-smith** [comment]
Ugghhh, wait until I PR the dependencies first!

**Comment by lbodor** [comment]
:+1:

**Pull request merged**
