### PR TITLE
Reformat header & footer

### PR DESCRIPTION
**Pull request by frankfu03**

### CODE REVIEW

**Comment by lbodor** [comment]
Is this a new kind of test failure? There is no usual mention of an unexpected alert popup.

**Comment by frankfu03** [comment]
Yes, it was introduced by the rename of the "NEW" buttons in previous merge. 

For example, the error message is: 
       Failed: No element found using locator: by.buttonText("New Collocation Information")

Since the "New Collocation Information" button was renamed to "New", so the e2e test couldn't find the button element. I'll fix them in a new PR.

**Comment by lbodor** [comment]
OK, great. I think we should merge that new PR first and rebase to potentially uncover any new problems with the 2 current PRs.

**Comment by frankfu03** [comment]
The PR for fixing e2e "New" button name issue has been merged.

**Pull request merged**
