### PR TITLE
Refactor e2e tests

### PR DESCRIPTION
**Pull request by frankfu03**

### CODE REVIEW

**Comment by lbodor** [comment]
Could you split these up into three pull requests please.

**Comment by frankfu03** [comment]
The 19 e2e test suites in site-log-groups have been merged into 2 suites, which significantly reduced the total e2e testing time: 30 m -> 11 m on my localhost; 25 m -> 8.6 m in Travis CI.

**Comment by frankfu03** [comment]
OK, I can split this PR into 3 separate PRs, but the first two PRs are likely fail in e2e tests..

**Comment by lbodor** [comment]
Is that because of the altering issue? If yes, you could first submit the fix for the altering issue.

**Comment by frankfu03** [comment]
No, the altering issue will be another PR. Maybe I can submit the third commit first, which fix the unexpected "alert" issue when running reload of the sitelog page.

**Comment by lbodor** [comment]
Sounds good

**Pull request closed without merging**
