### PR TITLE
Ng2 bootstrap

### PR DESCRIPTION
**Pull request by frankfu03**
Please review and merge it to master if it works fine. Thanks.

### CODE REVIEW

**Comment by oehm-smith** [comment]
I don't know it that well, but it looks odd that you need to include it twice.  Are you sure both are required.  I would have thought the one in the project config would have been all that is required.  Could you confirm?

**Comment by frankfu03** [comment]
Yeah, it is odd. I was asked to do a merge before doing rebase. So there are duplicate comments. There are only 4 lines added to 3 files.

**Comment by frankfu03** [comment]
"ng2-bootstrap" and "moment" were added to package.json for installing dependencies into node_modules; "ng2-bootstrap/ng2-bootstrap" added to tools/config/seed.config.ts
is used for importing modules from ng2-bootstrap in JS. So I can confirm that all 4 lines added are needed.

**Comment by oehm-smith** [comment]
So with things how they are (after rebase / merge), can you confirm you do need to modify the seed.config.ts - as I understood it, to customise you only modify the project.config.ts.  That is what the angular2-seed doco says.  In https://github.com/mgechev/angular2-seed/wiki/Architecture-and-usage-of-angular2-seed is 

### Config

The project defines a base configuration inside: tools/config/seed.config.ts. The config can be easily overridden in: tools/config/project.config.ts.

So could you double-check you need that modification.  And if you do can you make it to the project config?

**Comment by frankfu03** [comment]
Ok. I may remove the new line "'ng2-bootstrap/ng2-bootstrap':  ..." from seed.config.ts. It seems the UI still works fine after having removed it. I'll double check it

But we should be aware that "'ng2-bootstrap/ng2-bootstrap': 'node_modules/ng2-bootstrap/bundles/ng2-bootstrap.js'," in seed.config.ts is defining a path that is to be used for "import {DROPDOWN_DIRECTIVES} from 'ng2-bootstrap/ng2-bootstrap';" This idea comes from the Angular2 seed project which defined "'@angular/forms': `node_modules/@angular/forms/bundles/forms.umd.js`," for "import { REACTIVE_FORM_DIRECTIVES } from '@angular/forms';" in home.component.ts.

**Comment by oehm-smith** [comment]
If needed, can it go in the project.config.ts instead?

**Comment by frankfu03** [comment]
It seems that it cannot be defined in project.config.ts without significant changes. Because ProjectConfig extends from SeedConfig, we may merge both files if it is necessary. 

The project.config.ts defines .css and .js files to be injected into index.html, while seed.config.ts defines global variables and SYSTEM_CONFIG variables. 

I had another check and found out that the new line "'ng2-bootstrap/ng2-bootstrap': ..." added to seed.config.ts is actually injected into index.html as part of the System.config.

We may discuss this issue on Monday.

**Pull request closed without merging**
